---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: deviceshifu-camera
  name: deviceshifu-camera-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: hik-HTTP-driver
    driverImage:
  instructions: |
    instructions:
      move/up:
      move/down:
      move/left:
      move/right:
      capture:
      info:
      stream:
  telemetries: |
    telemetries:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-camera
  name: deviceshifu-camera
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-camera-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-camera
    workspace_id: a541c6dd-a89f-4fef-bde1-26b8e1a38f09
    device_id: ce4f6704-96b1-4dce-b016-c2fb211f8927
  name: deviceshifu-camera-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-camera-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-camera-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.50.0
          name: deviceshifu-http
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-camera-configmap
              mountPath: /etc/edgedevice/config
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "deviceshifu-camera-edgedevice"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
        - name: camera-python
          image: edgehub/camera-python:v0.0.3
          ports:
            - containerPort: 11112
              protocol: TCP
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-camera"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: IP_CAMERA_ADDRESS
              value: "bj-hikcamera-01.saifai.cn"
            - name: IP_CAMERA_RTSP_PORT
              value: "40554"
            - name: IP_CAMERA_HTTP_PORT
              value: "40081"
            - name: IP_CAMERA_CONTAINER_PORT
              value: "11112"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: IP_CAMERA_USERNAME
              value: "guest"
            - name: IP_CAMERA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camera-secret
                  key: IP_CAMERA_PASSWORD
                  optional: false
      volumes:
        - name: deviceshifu-camera-configmap
          configMap:
            name: deviceshifu-camera-configmap # extraContainer secret
      serviceAccountName: edgedevice-sa
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  labels:
    app: deviceshifu-camera
  name: deviceshifu-camera-edgedevice
  namespace: devices
spec:
  sku: "hik"
  connection: "Ethernet"
  address: "0.0.0.0:11112"
  protocol: "HTTP"
