---
# Source: deviceshifuchart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: deviceshifu-plc
  name: deviceshifu-plc-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: plc-HTTP-driver
    driverImage:
  instructions: |
    instructions:
      sendsinglebit:
      sendcontent:
      getcontent:
      getcpuordercode:
  telemetries: |
    telemetries:
---
# Source: deviceshifuchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-plc
  name: deviceshifu-plc
  namespace: deviceshifu
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-plc-deployment
  type: LoadBalancer
---
# Source: deviceshifuchart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-plc
  name: deviceshifu-plc-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-plc-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-plc-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.50.0
          name: deviceshifu-http
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-plc-configmap
              mountPath: /etc/edgedevice/config
              readOnly: true
          env:
          - name: EDGEDEVICE_NAME
            value: "deviceshifu-plc-edgedevice"
          - name: EDGEDEVICE_NAMESPACE
            value: "devices"
        - name: plc
          image: edgenesis/siemens-s7:v0.0.1
          ports:
            - containerPort: 11111
          env:
            - name: PLC_ADDRESS
              value: "bj-hikcamera-01.saifai.cn"
            - name: PLC_RACK
              value: "0"
            - name: PLC_SLOT
              value: "1"
            - name: PLC_PORT
              value: "40102"
            - name: PLC_CONTAINER_PORT
              value: "11111"
      volumes:
        - name: deviceshifu-plc-configmap
          configMap:
            name: deviceshifu-plc-configmap
      serviceAccountName: edgedevice-sa
---
# Source: deviceshifuchart/templates/edgedevice.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  labels:
    app: deviceshifu-plc
  name: deviceshifu-plc-edgedevice
  namespace: devices
spec:
  sku: "plc"
  connection: "Ethernet"
  address: "0.0.0.0:11111"
  protocol: "HTTP"
